apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bizrez-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - http:
      paths:
        - path: /apple
          pathType: Prefix
          backend:
            service: 
              name: apple-service
              port: 
                number: 5678
        - path: /banana
          pathType: Prefix
          backend:
            service:
              name: banana-service
              port: 
                number: 5678       
        - path: /influxdb
          pathType: Prefix
          backend:
            service:
              name: my-release-influxdb2
              port:
                number: 80
